import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Providers from "@/lib/providers";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/shared/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenShip: To keep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar/>
          {children}
        </Providers>
         <Toaster position="top-right" />
      </body>
    </html>
  );
}